services:
  postgres-db:
    container_name: postgresDb
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "db"]
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - '25432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared

  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      postgres-db:
        condition: service_healthy
    working_dir: /changelog
    command: >
      liquibase
      --searchPath=/changelog
      --changelog-file=db.changelog-master.yaml
      --url=jdbc:postgresql://postgres-db:5432/db
      --username=user
      --password=password
      --driver=org.postgresql.Driver
      update
    volumes:
      - ./changelog:/changelog
    networks:
      - shared

volumes:
  postgres-data:

networks:
  shared:
